### ISSUE TITLE
兄得，这项目跑不起来啊

### ISSUE THREAD

**Issue by Duaneding** [DesignHhuang/flowchart-angular6#2]
项目里用到了jquery，但是package.json里没有jq的依赖引用；手动装上jq，发现项目不停自动重启，浏览器快炸了

**Comment by ZCatherine** [comment]
楼上解决了吗，求助哇

**Comment by Duaneding** [comment]
项目差个jq，安装下jq的依赖包就能跑起来了------------------ 原始邮件 ------------------
发件人: "ZCatherine"<notifications@github.com>
发送时间: 2019年5月14日(星期二) 下午5:09
收件人: "DesignHhuang/flowchart-angular6"<flowchart-angular6@noreply.github.com>;
抄送: "Duaneding"<360227495@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [DesignHhuang/flowchart-angular6] 兄得，这项目跑不起来啊 (#2)



楼上解决了吗，求助哇
 
&mdash;

**Comment by ZCatherine** [comment]
那你遇到的重启嘞，没关系吗

**Comment by Duaneding** [comment]
重启问题是一个偶现bug，只出现了一次。------------------ 原始邮件 ------------------
发件人: "ZCatherine"<notifications@github.com>
发送时间: 2019年5月14日(星期二) 下午5:39
收件人: "DesignHhuang/flowchart-angular6"<flowchart-angular6@noreply.github.com>;
抄送: "Duaneding"<360227495@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [DesignHhuang/flowchart-angular6] 兄得，这项目跑不起来啊 (#2)



那你遇到的重启嘞，没关系吗
 
&mdash;

**Comment by DesignHhuang** [comment]
已更新至angular 7，部分代码修改不向下兼容
